apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nba-voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: skadare/nba-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://admin:admin123@mongodb:27017/nba?authSource=admin
